version: 2

registries:
  nuget.org:
    type: nuget-feed
    url: "https://api.nuget.org/v3/index.json"

updates:
  - package-ecosystem: "nuget"
    directories:
      - "/TramTimes.Cache.Stops"
      - "/TramTimes.Database.Schedules"
      - "/TramTimes.Database.Stops"
      - "/TramTimes.Search.Stops"
    registries:
      - nuget.org
    schedule:
      interval: "weekly"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "philvessey"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"